"use client";

import { useState, useMemo } from "react";
import { useModels } from "@/hooks/queries/useModels";
import { usePipelines } from "@/hooks/queries/usePipelines";
import { ModelCard } from "@/components/models/ModelCard";
import { GenerateModelsButton } from "@/components/models/GenerateModelsButton";
import { ModelCardSkeleton } from "@/components/skeletons/ModelCardSkeleton";
import { EmptyState } from "@/components/feedback/EmptyStates";
import { SlideIn } from "@/components/feedback/MicroInteractions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Boxes, Sparkles, Filter } from "lucide-react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { GeneratedModel, ModelLayer } from "@/types/models";

const layerFilters: { value: ModelLayer | "all"; label: string }[] = [
  { value: "all", label: "All Layers" },
  { value: "raw", label: "Raw" },
  { value: "canonical", label: "Canonical" },
  { value: "dimensional", label: "Dimensional" },
];

export default function ModelsPage() {
  const router = useRouter();
  const { data: models, isLoading, error } = useModels();
  const { data: pipelines } = usePipelines();
  const [layerFilter, setLayerFilter] = useState<ModelLayer | "all">("all");
  const [pipelineFilter, setPipelineFilter] = useState<string>("all");

  // Group models by pipeline
  const modelsByPipeline = useMemo(() => {
    if (!models) return {};

    let filteredModels = models;

    // Apply layer filter
    if (layerFilter !== "all") {
      filteredModels = filteredModels.filter((m) => m.layer === layerFilter);
    }

    // Apply pipeline filter
    if (pipelineFilter !== "all") {
      filteredModels = filteredModels.filter(
        (m) => m.pipeline_id === pipelineFilter
      );
    }

    // Group by pipeline
    return filteredModels.reduce((acc, model) => {
      const pipelineId = model.pipeline_id;
      if (!acc[pipelineId]) {
        acc[pipelineId] = [];
      }
      acc[pipelineId].push(model);
      return acc;
    }, {} as Record<string, GeneratedModel[]>);
  }, [models, layerFilter, pipelineFilter]);

  const getPipelineName = (pipelineId: string) => {
    const pipeline = pipelines?.find((p) => p.id === pipelineId);
    return pipeline?.name || `Pipeline ${pipelineId}`;
  };

  const handleModelClick = (modelId: string) => {
    router.push(`/models/${modelId}`);
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-3xl font-bold tracking-tight">AI Models</h1>
              <Badge variant="secondary" className="flex items-center gap-1">
                <Sparkles className="h-3 w-3" />
                AI-Generated
              </Badge>
            </div>
            <p className="text-muted-foreground">
              Dimensional models generated by AI from your data
            </p>
          </div>
          <GenerateModelsButton />
        </div>
        <ModelCardSkeleton count={6} />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-64">
        <p className="text-destructive">Error loading models</p>
      </div>
    );
  }

  const totalModels = models?.length || 0;
  const pipelineGroups = Object.entries(modelsByPipeline);

  return (
    <div className="space-y-6">
      <SlideIn direction="down" duration={0.3}>
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-3xl font-bold tracking-tight">AI Models</h1>
              <Badge variant="secondary" className="flex items-center gap-1">
                <Sparkles className="h-3 w-3" />
                AI-Generated
              </Badge>
            </div>
            <p className="text-muted-foreground">
              Dimensional models generated by AI from your data
            </p>
          </div>
          <GenerateModelsButton />
        </div>
      </SlideIn>

      {/* Filters */}
      {totalModels > 0 && (
        <SlideIn direction="up" delay={0.1}>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <Filter className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Filter by:</span>
            </div>
            <Select
              value={layerFilter}
              onValueChange={(value) => setLayerFilter(value as ModelLayer | "all")}
            >
              <SelectTrigger className="w-[150px]">
                <SelectValue placeholder="Layer" />
              </SelectTrigger>
              <SelectContent>
                {layerFilters.map((filter) => (
                  <SelectItem key={filter.value} value={filter.value}>
                    {filter.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select
              value={pipelineFilter}
              onValueChange={setPipelineFilter}
            >
              <SelectTrigger className="w-[200px]">
                <SelectValue placeholder="Pipeline" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Pipelines</SelectItem>
                {pipelines?.map((pipeline) => (
                  <SelectItem key={pipeline.id} value={pipeline.id}>
                    {pipeline.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {(layerFilter !== "all" || pipelineFilter !== "all") && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setLayerFilter("all");
                  setPipelineFilter("all");
                }}
              >
                Clear filters
              </Button>
            )}
          </div>
        </SlideIn>
      )}

      {/* Empty State */}
      {totalModels === 0 ? (
        <Card>
          <EmptyState
            icon={<Boxes className="h-10 w-10" />}
            title="No models generated yet"
            description="Use AI to automatically generate dimensional models (star schema) from your synced data. These models help you analyze your data more effectively."
            action={{
              label: "Generate Models",
              onClick: () => {},
            }}
          />
        </Card>
      ) : pipelineGroups.length === 0 ? (
        <Card className="p-8">
          <div className="text-center">
            <p className="text-muted-foreground">
              No models match your current filters.
            </p>
            <Button
              variant="outline"
              className="mt-4"
              onClick={() => {
                setLayerFilter("all");
                setPipelineFilter("all");
              }}
            >
              Clear filters
            </Button>
          </div>
        </Card>
      ) : (
        <motion.div
          className="space-y-8"
          initial="hidden"
          animate="visible"
          variants={{
            hidden: { opacity: 0 },
            visible: {
              opacity: 1,
              transition: {
                staggerChildren: 0.1,
                delayChildren: 0.2,
              },
            },
          }}
        >
          {pipelineGroups.map(([pipelineId, pipelineModels]) => (
            <motion.div
              key={pipelineId}
              variants={{
                hidden: { opacity: 0, y: 20 },
                visible: { opacity: 1, y: 0 },
              }}
            >
              <div className="flex items-center gap-3 mb-4">
                <h2 className="text-lg font-semibold">
                  {getPipelineName(pipelineId)}
                </h2>
                <Badge variant="outline">{pipelineModels.length} models</Badge>
              </div>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {pipelineModels.map((model, index) => (
                  <motion.div
                    key={model.id}
                    variants={{
                      hidden: { opacity: 0, scale: 0.95 },
                      visible: { opacity: 1, scale: 1 },
                    }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <ModelCard
                      model={model}
                      onClick={() => handleModelClick(model.id)}
                    />
                  </motion.div>
                ))}
              </div>
            </motion.div>
          ))}
        </motion.div>
      )}
    </div>
  );
}
